export const DEFAULT_CONFIGS = Object.freeze({
  "app.json": {
    schema: 1,
    appName: "PomBlock",
    timezone: "UTC",
    blocksCalendarName: "Blocks",
  },
  "calendars.json": {
    schema: 1,
    blocksCalendarId: null,
    busyCalendarIds: ["primary"],
  },
  "policies.json": {
    schema: 1,
    workHours: {
      start: "09:00",
      end: "18:00",
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    },
    generation: {
      autoEnabled: true,
      autoTime: "05:30",
      catchUpOnAppStart: true,
      placementStrategy: "keep",
      maxShiftMinutes: 120,
      maxAutoBlocksPerDay: 24,
      maxRelocationsPerSync: 50,
      createIfNoSlot: false,
      respectSuppression: true,
      todayAutoGenerate: true,
      generateOnAppStart: true,
    },
    timer: {
      defaultAutoDriveMode: "manual",
      overrunPolicy: "wait",
    },
    blockDurationMinutes: 60,
    breakDurationMinutes: 5,
    minBlockGapMinutes: 0,
  },
  "templates.json": {
    schema: 1,
    templates: [],
  },
  "routines.json": {
    schema: 1,
    routines: [],
  },
  "recipes.json": {
    schema: 1,
    recipes: [],
  },
  "modules.json": {
    schema: 1,
    modules: [
      {
        id: "mod-deep-work-init",
        name: "Deep Work Init",
        category: "Focus Work",
        description: "Environment prep",
        icon: "spark",
        stepType: "micro",
        durationMinutes: 5,
        checklist: ["Close distracting tabs", "Set Slack to Away", "Enable Do Not Disturb"],
        pomodoro: null,
        overrunPolicy: "wait",
        executionHints: {
          allowSkip: true,
          mustCompleteChecklist: false,
          autoAdvance: true,
        },
      },
      {
        id: "mod-pomodoro-focus",
        name: "Pomodoro Focus",
        category: "Focus Work",
        description: "25m work block",
        icon: "timer",
        stepType: "pomodoro",
        durationMinutes: 25,
        checklist: ["Focus on one task only", "No context switching"],
        pomodoro: {
          focusSeconds: 1500,
          breakSeconds: 300,
          cycles: 1,
          longBreakSeconds: 900,
          longBreakEvery: 4,
        },
        overrunPolicy: "wait",
        executionHints: {
          allowSkip: true,
          mustCompleteChecklist: false,
          autoAdvance: true,
        },
      },
      {
        id: "mod-two-min-triage",
        name: "2m Triage",
        category: "Communication",
        description: "Quick inbox sort",
        icon: "mail",
        stepType: "micro",
        durationMinutes: 2,
        checklist: ["Reply, archive, or defer", "No deep replies"],
        pomodoro: null,
        overrunPolicy: "wait",
        executionHints: {
          allowSkip: true,
          mustCompleteChecklist: false,
          autoAdvance: true,
        },
      },
    ],
  },
  "overrides.json": {
    schema: 1,
    mode: "none",
    value: {},
  },
});


